using System.ComponentModel;
namespace FF1Lib
{
	public enum MapIndex : byte
	{
		ConeriaTown = 0,
		Pravoka = 1,
		Elfland = 2,
		Melmond = 3,
		CrescentLake = 4,
		Gaia = 5,
		Onrac = 6,
		Lefein = 7,
		ConeriaCastle1F = 8,
		ElflandCastle = 9,
		NorthwestCastle = 10,
		CastleOrdeals1F = 11,
		TempleOfFiends = 12,
		EarthCaveB1 = 13,
		GurguVolcanoB1 = 14,
		IceCaveB1 = 15,
		Cardia = 16,
		BahamutCaveB1 = 17,
		Waterfall = 18,
		DwarfCave = 19,
		MatoyasCave = 20,
		SardasCave = 21,
		MarshCaveB1 = 22,
		MirageTower1F = 23,
		ConeriaCastle2F = 24,
		CastleOrdeals2F = 25,
		CastleOrdeals3F = 26,
		MarshCaveB2 = 27,
		MarshCaveB3 = 28,
		EarthCaveB2 = 29,
		EarthCaveB3 = 30,
		EarthCaveB4 = 31,
		EarthCaveB5 = 32,
		GurguVolcanoB2 = 33,
		GurguVolcanoB3 = 34,
		GurguVolcanoB4 = 35,
		GurguVolcanoB5 = 36,
		IceCaveB2 = 37,
		IceCaveB3 = 38,
		BahamutCaveB2 = 39,
		MirageTower2F = 40,
		MirageTower3F = 41,
		SeaShrineB5 = 42,
		SeaShrineB4 = 43,
		SeaShrineB3 = 44,
		SeaShrineB2 = 45,
		SeaShrineB1 = 46,
		SkyPalace1F = 47,
		SkyPalace2F = 48,
		SkyPalace3F = 49,
		SkyPalace4F = 50,
		SkyPalace5F = 51,
		TempleOfFiendsRevisited1F = 52,
		TempleOfFiendsRevisited2F = 53,
		TempleOfFiendsRevisited3F = 54,
		TempleOfFiendsRevisitedEarth = 55,
		TempleOfFiendsRevisitedFire = 56,
		TempleOfFiendsRevisitedWater = 57,
		TempleOfFiendsRevisitedAir = 58,
		TempleOfFiendsRevisitedChaos = 59,
		TitansTunnel = 60,
	}
	public enum MapLocation
	{
		StartingLocation,
		AirshipLocation,
		Coneria,
		Pravoka,
		Elfland,
		Melmond,
		CrescentLake,
		Gaia,
		Onrac,
		Lefein,
		Caravan,
		ConeriaCastle1,
		ConeriaCastle2,
		ConeriaCastleRoom1,
		ConeriaCastleRoom2,
		ElflandCastle,
		ElflandCastleRoom1,
		NorthwestCastle,
		NorthwestCastleRoom2,
		CastleOrdeals1,
		CastleOrdealsMaze,
		CastleOrdealsTop,
		EarthCave1,
		EarthCave2,
		EarthCaveVampire,
		EarthCave4,
		EarthCaveLich,
		GurguVolcano1,
		GurguVolcano2,
		GurguVolcano3,
		GurguVolcano4,
		GurguVolcano5,
		GurguVolcano6,
		GurguVolcanoKary,
		IceCave1,
		IceCave2,
		IceCave3,
		IceCavePitRoom,
		IceCave5,
		IceCaveBackExit,
		IceCaveFloater,
		Cardia1,
		Cardia2,
		BahamutCave1,
		BahamutCave2,
		Cardia4,
		Cardia5,
		Cardia6,
		Waterfall,
		DwarfCave,
		DwarfCaveRoom3,
		MatoyasCave,
		SardasCave,
		MarshCave1,
		MarshCaveTop,
		MarshCave3,
		MarshCaveBottom,
		MarshCaveBottomRoom13,
		MarshCaveBottomRoom14,
		MarshCaveBottomRoom16,
		MirageTower1,
		MirageTower2,
		MirageTower3,
		SeaShrine1,
		SeaShrine2,
		SeaShrine2Room2,
		SeaShrineMermaids,
		SeaShrine4,
		SeaShrine5,
		SeaShrine6,
		SeaShrine7,
		SeaShrine8,
		SeaShrineKraken,
		SkyPalace1,
		SkyPalace2,
		SkyPalace3,
		SkyPalaceMaze,
		SkyPalaceTiamat,
		TempleOfFiends1,
		TempleOfFiends1Room1,
		TempleOfFiends1Room2,
		TempleOfFiends1Room3,
		TempleOfFiends1Room4,
		TempleOfFiends2,
		TempleOfFiends3,
		TempleOfFiendsPhantom,
		TempleOfFiendsEarth,
		TempleOfFiendsFire,
		TempleOfFiendsWater,
		TempleOfFiendsAir,
		TempleOfFiendsChaos,
		TitansTunnelEast,
		TitansTunnelWest,
		TitansTunnelRoom,
		IceCaveDummy,
		None
	}
	public enum ExitTeleportIndex : byte
	{
		ExitTitanE = 0,
		ExitTitanW = 1,
		ExitIceCave = 2,
		ExitCastleOrdeals = 3,
		ExitCastleConeria = 4,
		ExitEarthCave = 5,
		ExitGurguVolcano = 6,
		ExitSeaShrine = 7,
		ExitSkyPalace = 8,
		ExitUnused1 = 9,
		ExitUnused2 = 10,
		ExitUnused3 = 11,
		ExitUnused4 = 12,
		ExitUnused5 = 13,
		ExitUnused6 = 14,
		ExitUnused7 = 15,
		None = 255
	}
	public enum TeleportIndex : byte
	{
		ConeriaCastle2 = 0, // to go upstairs
		TempleOfFiends2 = 1,
		MarshCaveTop = 2,
		MarshCave3 = 3,
		MarshCaveBottom = 4,
		EarthCave2 = 5,
		EarthCaveVampire = 6,
		EarthCave4 = 7,
		EarthCaveLich = 8,
		GurguVolcano2 = 9,
		GurguVolcano3 = 10,
		GurguVolcano4 = 11,
		GurguVolcano5 = 12,
		GurguVolcano6 = 13,
		GurguVolcanoKary = 14,
		IceCave2 = 15,
		IceCave3 = 16,
		IceCavePitRoom = 17,
		IceCave5 = 18,
		IceCave6 = 19,
		IceCave7 = 20,
		IceCave8 = 21,
		CastleOrdealsMaze = 22,
		CastleOrdealsTop = 23,
		CastleOrdealsBack = 24,
		BahamutsRoom = 25,
		CastleOrdeals4 = 26,
		CastleOrdeals5 = 27,
		CastleOrdeals6 = 28,
		CastleOrdeals7 = 29,
		CastleOrdeals8 = 30,
		CastleOrdeals9 = 31,
		SeaShrine1 = 32,
		SeaShrine2 = 33,
		SeaShrineMermaids = 34,
		SeaShrine4 = 35,
		SeaShrine5 = 36,
		SeaShrine6 = 37,
		SeaShrine7 = 38,
		SeaShrine8 = 39,
		SeaShrineKraken = 40,
		MirageTower2 = 41,
		MirageTower3 = 42,
		SkyPalace1 = 43,
		SkyPalace2 = 44,
		SkyPalace3 = 45,
		SkyPalaceMaze = 46,
		SkyPalaceTiamat = 47,
		TempleOfFiends3 = 48,
		TempleOfFiends4 = 49,
		TempleOfFiends5 = 50,
		TempleOfFiends6 = 51,
		TempleOfFiends7 = 52,
		TempleOfFiends8 = 53,
		TempleOfFiends9 = 54,
		TempleOfFiends10 = 55,
		TempleOfFiends11 = 56,
		TempleOfFiends12 = 57,
		CastleOrdeals10 = 58,
		CastleOrdeals11 = 59,
		CastleOrdeals12 = 60,
		CastleOrdeals13 = 61,
		ConeriaCastleBack = 62, // going back down
		RescuePrincess = 63,
		Overworld = 255
	}
	public enum OverworldTeleportIndex : byte
	{
		Cardia1 = 0,
		Coneria = 1,
		Pravoka = 2,
		Elfland = 3,
		Melmond = 4,
		CrescentLake = 5,
		Gaia = 6,
		Onrac = 7,
		Lefein = 8,
		ConeriaCastle1 = 9,
		ElflandCastle = 10,
		NorthwestCastle = 11,
		CastleOrdeals1 = 12,
		TempleOfFiends1 = 13,
		EarthCave1 = 14,
		GurguVolcano1 = 15,
		IceCave1 = 16,
		Cardia2 = 17,
		BahamutCave1 = 18,
		Waterfall = 19,
		DwarfCave = 20,
		MatoyasCave = 21,
		SardasCave = 22,
		MarshCave1 = 23,
		MirageTower1 = 24,
		TitansTunnelEast = 25,
		TitansTunnelWest = 26,
		Cardia4 = 27,
		Cardia5 = 28,
		Cardia6 = 29,
		Unused1 = 30,
		Unused2 = 31,
		None = 0xff
	}
	public enum Backdrop : byte
	{
		Grass = 0x00,
		MarshCave = 0x01,
		Cave = 0x02,
		Water = 0x03,
		Forest = 0x04,
		TempleOfFiends = 0x05,
		Desert = 0x06,
		Marsh = 0x07,
		EarthCave = 0x08,
		Castle = 0x09,
		River = 0x0A,
		Tower = 0x0B,
		SeaShrine = 0x0C,
		IceCave	= 0x0D,
		Volcano	= 0x0E,
		Waterfall = 0x0F,
	}

	public enum Classes : byte
	{
		Fighter = 0x00,
		Thief,
		BlackBelt,
		RedMage,
		WhiteMage,
		BlackMage,
		Knight,
		Ninja,
		Master,
		RedWizard,
		WhiteWizard,
		BlackWizard
	}

	public enum SpellSlots : int
	{
		White1Slot1 = 0x00,
		White1Slot2,
		White1Slot3,
		White1Slot4,
		Black1Slot1,
		Black1Slot2,
		Black1Slot3,
		Black1Slot4,
		White2Slot1,
		White2Slot2,
		White2Slot3,
		White2Slot4,
		Black2Slot1,
		Black2Slot2,
		Black2Slot3,
		Black2Slot4,
		White3Slot1,
		White3Slot2,
		White3Slot3,
		White3Slot4,
		Black3Slot1,
		Black3Slot2,
		Black3Slot3,
		Black3Slot4,
		White4Slot1,
		White4Slot2,
		White4Slot3,
		White4Slot4,
		Black4Slot1,
		Black4Slot2,
		Black4Slot3,
		Black4Slot4,
		White5Slot1,
		White5Slot2,
		White5Slot3,
		White5Slot4,
		Black5Slot1,
		Black5Slot2,
		Black5Slot3,
		Black5Slot4,
		White6Slot1,
		White6Slot2,
		White6Slot3,
		White6Slot4,
		Black6Slot1,
		Black6Slot2,
		Black6Slot3,
		Black6Slot4,
		White7Slot1,
		White7Slot2,
		White7Slot3,
		White7Slot4,
		Black7Slot1,
		Black7Slot2,
		Black7Slot3,
		Black7Slot4,
		White8Slot1,
		White8Slot2,
		White8Slot3,
		White8Slot4,
		Black8Slot1,
		Black8Slot2,
		Black8Slot3,
		Black8Slot4,
		None
	}

	public enum GameModes
	{
		[Description("Standard")]
		Standard = 0,
		[Description("Deep Dungeon")]
		DeepDungeon,
		[Description("No Overworld")]
		NoOverworld,
	}
}
