//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAsm {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DotNetAsm.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AssertionFailure {
            get {
                return ResourceManager.GetString("AssertionFailure", resourceCulture);
            }
        }
        
        public static string BadExpression {
            get {
                return ResourceManager.GetString("BadExpression", resourceCulture);
            }
        }
        
        public static string CannotResolveAnonymousLabel {
            get {
                return ResourceManager.GetString("CannotResolveAnonymousLabel", resourceCulture);
            }
        }
        
        public static string ClosureDoesNotCloseBlock {
            get {
                return ResourceManager.GetString("ClosureDoesNotCloseBlock", resourceCulture);
            }
        }
        
        public static string ClosureDoesNotCloseMacro {
            get {
                return ResourceManager.GetString("ClosureDoesNotCloseMacro", resourceCulture);
            }
        }
        
        public static string CouldNotProcessBinary {
            get {
                return ResourceManager.GetString("CouldNotProcessBinary", resourceCulture);
            }
        }
        
        public static string DefininingUnknownType {
            get {
                return ResourceManager.GetString("DefininingUnknownType", resourceCulture);
            }
        }
        
        public static string Depricated {
            get {
                return ResourceManager.GetString("Depricated", resourceCulture);
            }
        }
        
        public static string DirectiveTakesNoArguments {
            get {
                return ResourceManager.GetString("DirectiveTakesNoArguments", resourceCulture);
            }
        }
        
        public static string EncodingNameNotValid {
            get {
                return ResourceManager.GetString("EncodingNameNotValid", resourceCulture);
            }
        }
        
        public static string FilenameNotSpecified {
            get {
                return ResourceManager.GetString("FilenameNotSpecified", resourceCulture);
            }
        }
        
        public static string FilePreviouslyIncluded {
            get {
                return ResourceManager.GetString("FilePreviouslyIncluded", resourceCulture);
            }
        }
        
        public static string IllegalQuantity {
            get {
                return ResourceManager.GetString("IllegalQuantity", resourceCulture);
            }
        }
        
        public static string InvalidParamRef {
            get {
                return ResourceManager.GetString("InvalidParamRef", resourceCulture);
            }
        }
        
        public static string InvalidPCAssignment {
            get {
                return ResourceManager.GetString("InvalidPCAssignment", resourceCulture);
            }
        }
        
        public static string LabelNotDefined {
            get {
                return ResourceManager.GetString("LabelNotDefined", resourceCulture);
            }
        }
        
        public static string LabelNotLeft {
            get {
                return ResourceManager.GetString("LabelNotLeft", resourceCulture);
            }
        }
        
        public static string LabelNotValid {
            get {
                return ResourceManager.GetString("LabelNotValid", resourceCulture);
            }
        }
        
        public static string LabelRedefinition {
            get {
                return ResourceManager.GetString("LabelRedefinition", resourceCulture);
            }
        }
        
        public static string MacroParamIncorrect {
            get {
                return ResourceManager.GetString("MacroParamIncorrect", resourceCulture);
            }
        }
        
        public static string MacroParamNotSpecified {
            get {
                return ResourceManager.GetString("MacroParamNotSpecified", resourceCulture);
            }
        }
        
        public static string MacroRedefinition {
            get {
                return ResourceManager.GetString("MacroRedefinition", resourceCulture);
            }
        }
        
        public static string MissingClosure {
            get {
                return ResourceManager.GetString("MissingClosure", resourceCulture);
            }
        }
        
        public static string MissingClosureMacro {
            get {
                return ResourceManager.GetString("MissingClosureMacro", resourceCulture);
            }
        }
        
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        public static string PCOverflow {
            get {
                return ResourceManager.GetString("PCOverflow", resourceCulture);
            }
        }
        
        public static string PStringSizeTooLarge {
            get {
                return ResourceManager.GetString("PStringSizeTooLarge", resourceCulture);
            }
        }
        
        public static string QuoteStringNotEnclosed {
            get {
                return ResourceManager.GetString("QuoteStringNotEnclosed", resourceCulture);
            }
        }
        
        public static string RecursiveMacro {
            get {
                return ResourceManager.GetString("RecursiveMacro", resourceCulture);
            }
        }
        
        public static string TooFewArguments {
            get {
                return ResourceManager.GetString("TooFewArguments", resourceCulture);
            }
        }
        
        public static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        public static string TooManyCharacters {
            get {
                return ResourceManager.GetString("TooManyCharacters", resourceCulture);
            }
        }
        
        public static string TypeDefinitionError {
            get {
                return ResourceManager.GetString("TypeDefinitionError", resourceCulture);
            }
        }
        
        public static string TypeNameReserved {
            get {
                return ResourceManager.GetString("TypeNameReserved", resourceCulture);
            }
        }
        
        public static string UnknownInstruction {
            get {
                return ResourceManager.GetString("UnknownInstruction", resourceCulture);
            }
        }
    }
}
