//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAsm {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Patterns {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Patterns() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DotNetAsm.Patterns", typeof(Patterns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SymbolBasic {
            get {
                return ResourceManager.GetString("SymbolBasic", resourceCulture);
            }
        }
        
        internal static string SymbolChar {
            get {
                return ResourceManager.GetString("SymbolChar", resourceCulture);
            }
        }
        
        internal static string SymbolDot {
            get {
                return ResourceManager.GetString("SymbolDot", resourceCulture);
            }
        }
        
        internal static string SymbolFull {
            get {
                return ResourceManager.GetString("SymbolFull", resourceCulture);
            }
        }
        
        internal static string SymbolUnderscore {
            get {
                return ResourceManager.GetString("SymbolUnderscore", resourceCulture);
            }
        }
        
        internal static string SymbolUnicode {
            get {
                return ResourceManager.GetString("SymbolUnicode", resourceCulture);
            }
        }
        
        internal static string SymbolUnicodeNoLeadingUnderscore {
            get {
                return ResourceManager.GetString("SymbolUnicodeNoLeadingUnderscore", resourceCulture);
            }
        }
        
        internal static string SymbolUnicodeChar {
            get {
                return ResourceManager.GetString("SymbolUnicodeChar", resourceCulture);
            }
        }
        
        internal static string SymbolUnicodeDot {
            get {
                return ResourceManager.GetString("SymbolUnicodeDot", resourceCulture);
            }
        }
        
        internal static string SymbolUnicodeFull {
            get {
                return ResourceManager.GetString("SymbolUnicodeFull", resourceCulture);
            }
        }
    }
}
