FROM mcr.microsoft.com/dotnet/sdk:10.0
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash && \. "$HOME/.nvm/nvm.sh" && nvm install 22 && npm install -g netlify-cli
RUN apt update && apt install -y jq curl
