FROM mcr.microsoft.com/dotnet/sdk:10.0
SHELL ["/bin/bash", "--login", "-c"]
RUN curl -sL https://deb.nodesource.com/setup_22.x | bash - && apt-get install -y nodejs jq curl
RUN npm install -g netlify-cli
